#!/bin/bash

# Author: Maria Nattestad
# Email: mnattest@cshl.edu
# This script is part of Assemblytics, a program to detect and analyze structural variants from an assembly aligned to a reference genome using MUMmer. 


USAGE="Assemblytics delta output_prefix unique_length_required path_to_R_scripts"
if [ -z "$1" ]
  then
    echo "ERROR in Assemblytics: No delta file given"
    echo "Usage:"
    echo $USAGE
    exit
fi
if [ -z "$2" ]
  then
    echo "ERROR in Assemblytics: No output prefix given"
    echo "Usage:"
    echo $USAGE
    exit
fi
if [ -z "$3" ]
  then
    echo "ERROR in Assemblytics: No unique length requirement parameter given"
    echo "Usage:"
    echo $USAGE
    exit
fi
if [ -z "$4" ]
  then
    echo "ERROR in Assemblytics: No path to R scripts given. R scripts are only necessary for plotting results at the end, so if the path does not exist, only the plots will be missing from the results."
    echo "Usage:"
    echo $USAGE
    exit
fi


DELTA=${1?"$USAGE"}
OUTPUT_PREFIX=${2?"$USAGE"}
UNIQUE_LENGTH=${3?"$USAGE"}
PATH_TO_R_SCRIPTS=${4?"$USAGE"}

>&2 echo Input delta file: $DELTA
>&2 echo Output prefix: $OUTPUT_PREFIX
>&2 echo Unique anchor length: $UNIQUE_LENGTH
>&2 echo Path to R scripts: $PATH_TO_R_SCRIPTS

MINIMUM_SIZE=1
#MAXIMUM_SIZE=$UNIQUE_LENGTH
MAXIMUM_SIZE=1000000
echo "${OUTPUT_PREFIX##*/}"

echo "STARTING,DONE,Starting unique anchor filtering."

>&2 echo "1. Filter delta file"
Assemblytics_uniq_anchor.py --delta $DELTA --unique-length $UNIQUE_LENGTH --keep-small-uniques --out $OUTPUT_PREFIX
if [ -e $OUTPUT_PREFIX.Assemblytics.unique_length_filtered_l$UNIQUE_LENGTH.delta.gz ];
then
    echo "UNIQFILTER,DONE,Step 1: Assemblytics_uniq_anchor.py completed successfully. Now finding variants between alignments." 
    >&2 echo "2. Finding variants between alignments"
    Assemblytics_between_alignments.pl $OUTPUT_PREFIX.coords.tab $MINIMUM_SIZE $MAXIMUM_SIZE all-chromosomes exclude-longrange bed > $OUTPUT_PREFIX.variants_between_alignments.bed

    if [ -e $OUTPUT_PREFIX.variants_between_alignments.bed ];
    then
        echo "BETWEEN,DONE,Step 2: Assemblytics_between_alignments.pl completed successfully. Now finding variants within alignments."
        >&2 echo "3. Finding variants within alignments"
        Assemblytics_within_alignment.py --delta $OUTPUT_PREFIX.Assemblytics.unique_length_filtered_l$UNIQUE_LENGTH.delta.gz --min $MINIMUM_SIZE > $OUTPUT_PREFIX.variants_within_alignments.bed

        if [ -e $OUTPUT_PREFIX.variants_within_alignments.bed ];
        then
            echo "WITHIN,DONE,Step 3: Assemblytics_within_alignment.py completed successfully. Now combining the two sets of variants together."
            >&2 echo "4. Combine variants between and within alignments";
            HEADER="#reference\tref_start\tref_stop\tID\tsize\tstrand\ttype\tref_gap_size\tquery_gap_size\tquery_coordinates\tmethod"
            cat <(echo -e $HEADER) $OUTPUT_PREFIX.variants_within_alignments.bed $OUTPUT_PREFIX.variants_between_alignments.bed > $OUTPUT_PREFIX.Assemblytics_structural_variants.bed

            if [ -e $OUTPUT_PREFIX.Assemblytics_structural_variants.bed ];
            then 
                echo "COMBINE,DONE,Step 4: Variants combined successfully. Now generating figures and summary statistics." 
                
                Rscript $PATH_TO_R_SCRIPTS/Assemblytics_variant_charts.R $OUTPUT_PREFIX $MINIMUM_SIZE $MAXIMUM_SIZE

                Assemblytics_index.py -coords $OUTPUT_PREFIX.coords.csv -out $OUTPUT_PREFIX
                
                Rscript $PATH_TO_R_SCRIPTS/Assemblytics_dotplot.R $OUTPUT_PREFIX

                cat $OUTPUT_PREFIX.coords.tab | awk '{print $7,$5}' OFS='\t' | sort | uniq | sort -k2,2nr >  $OUTPUT_PREFIX.coords.ref.genome
                cat $OUTPUT_PREFIX.coords.tab | awk '{print $8,$6}' OFS='\t' | sort | uniq | sort -k2,2nr >  $OUTPUT_PREFIX.coords.query.genome
                
                Rscript $PATH_TO_R_SCRIPTS/Assemblytics_Nchart.R $OUTPUT_PREFIX
                
                Assemblytics_summary.py -i $OUTPUT_PREFIX.Assemblytics_structural_variants.bed -min $MINIMUM_SIZE -max $MAXIMUM_SIZE > $OUTPUT_PREFIX.Assemblytics_structural_variants.summary

                if grep -q "Total" $OUTPUT_PREFIX.Assemblytics_structural_variants.summary; 
                then
                    echo "SUMMARY,DONE,Step 5: Assemblytics_summary.py completed successfully" 
                else
                    echo "SUMMARY,FAIL,Step 5: Assemblytics_summary.py failed"
                fi
            
            else
                echo "COMBINE,FAIL,Step 4: combining variants failed" 
            fi
        else
            echo "WITHIN,FAIL,Step 3: Assemblytics_within_alignment.py failed: Possible problem before this step or with Python on server."
        fi
    else
        echo "BETWEEN,FAIL,Step 2: Assemblytics_between_alignments.pl failed: Possible problem with Perl or show-coords on server." 
    fi
else
    echo "UNIQFILTER,FAIL,Step 1: Assemblytics_uniq_anchor.py failed: Possible problem with Python or Python packages on server." 
fi

